<%@ Page Title="Instância de fluxo" Language="C#" Inherits="Benner.Tecnologia.Workflow.WebApp.WorkflowInstancePage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="INSTNCIADEFLUXO" Title="Instância de fluxo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOINSTANCIAS.MONITOR.FORM" IncludeRecordInRecentItems="True" UserDefinedLinkVisible="True" UserDefinedCommandsVisible="True" PageWidgetHandle="139" Level="15" Order="10"  />
        <wes:SimpleGrid runat="server" ID="ATIVIDADESREALIZADAS" Title="Atividades realizadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="INSTNCIADEFLUXO" ChromeState="Normal" EntityViewName="Z_WFMODELOINSTANCIAATIVIDADES.MONITOR.GRID" CanDelete="False" CanUpdate="False" CanInsert="False" UserDefinedSelectColumnVisible="True" Mode="Selectable" UserDefinedPageSize="100" SystemFilterOnly="False" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.MODELOINSTANCIA = @CAMPO(HANDLE)" FormUrl="~/wfl/a/m/atividade.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="140" Level="15" Order="20"  />
        <wes:CustomUserControl runat="server" ID="IMAGEM" Title="Imagem" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="INSTNCIADEFLUXO" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" UserControlName="~/uc/WorkflowImage.ascx" PageWidgetHandle="141" Level="15" Order="24"  />
        <wes:SimpleGrid runat="server" ID="SUBFLUXOS" Title="Sub-fluxos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="INSTNCIADEFLUXO" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOINSTANCIAS.MONITOR.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.SUPERIOR = @CAMPO(HANDLE)" FormUrl="~/wfl/a/m/instancia.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="142" Level="15" Order="25"  />
        <wes:SimpleGrid runat="server" ID="LEMBRETES" Title="Lembretes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="INSTNCIADEFLUXO" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFLEMBRETES.MONITOR.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.MODELOINSTANCIA = @CAMPO(HANDLE)" UserDefinedDisableRowSelection="False" PageWidgetHandle="143" Level="15" Order="30"  />
        <wes:SimpleGrid runat="server" ID="MENSAGENSDEERRO" Title="Mensagens de erro" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="INSTNCIADEFLUXO" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOINSTANCIAEXCECOES.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.MODELOINSTANCIA = @CAMPO(HANDLE)" FormUrl="~/wfl/a/t/Z_WFMODELOINSTANCIAEXCECOES.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="144" Level="15" Order="40"  />
        </div>
    
      </asp:Content>
    