<%@ Page Title="Instância" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="WFL_TASKS_INSTANCE" Title="Instância de fluxo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOINSTANCIAS.INBOX.FORM" IncludeRecordInRecentItems="True" UserDefinedLinkVisible="True" UserDefinedCommandsVisible="True" PageWidgetHandle="78" Level="15" Order="10"  />
        <wes:SimpleGrid runat="server" ID="WFL_TASKS_INSTANCE_ATIVITIES" Title="Atividades realizadas" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="WFL_TASKS_INSTANCE" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOINSTANCIAATIVIDADES.INBOX.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.MODELOINSTANCIA = @CAMPO(HANDLE)" FormUrl="~/wfl/a/t/atividade.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="79" Level="15" Order="20"  />
        <wes:CustomUserControl runat="server" ID="IMAGEM" Title="Imagem" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="WFL_TASKS_INSTANCE" ChromeState="Minimized" CanDelete="True" CanUpdate="True" CanInsert="True" SystemInstanceName="WORKFLOW" UserControlName="~/uc/WorkflowImage.ascx" PageWidgetHandle="80" Level="15" Order="24"  />
        <wes:SimpleGrid runat="server" ID="SUBFLUXOS" Title="Sub-fluxos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="WFL_TASKS_INSTANCE" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOINSTANCIAS.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.SUPERIOR = @CAMPO(HANDLE)" FormUrl="~/wfl/a/t/instancia.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="81" Level="15" Order="25"  />
        <wes:SimpleGrid runat="server" ID="WF_TASKS_REMINDERS" Title="Lembretes" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="WFL_TASKS_INSTANCE" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFLEMBRETES.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.MODELOINSTANCIA = @CAMPO(HANDLE)" UserDefinedDisableRowSelection="False" PageWidgetHandle="82" Level="15" Order="50"  />
        <wes:SimpleGrid runat="server" ID="WF_TASKS_ERRORS" Title="Mensagens de erro" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="WFL_TASKS_INSTANCE" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOINSTANCIAEXCECOES.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.MODELOINSTANCIA = @CAMPO(HANDLE)" UserDefinedDisableRowSelection="False" PageWidgetHandle="83" Level="15" Order="60"  />
        </div>
    
      </asp:Content>
    