//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Biblioteca.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela EDITORAS
    /// </summary>
    public partial interface IEditoras : IEntityBase
    {
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 50
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        string Nome
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela EDITORAS
    /// </summary>
    public partial interface IEditorasDao : IBusinessEntityDao<IEditoras>
    {
    }
    
    /// <summary>
    /// DAO para a tabela EDITORAS
    /// </summary>
    public partial class EditorasDao : BusinessEntityDao<Editoras, IEditoras>, IEditorasDao
    {
        
        public static EditorasDao CreateInstance()
        {
            return CreateInstance<EditorasDao>();
        }
    }
    
    /// <summary>
    /// Editoras
    /// </summary>
    [EntityDefinitionName("EDITORAS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Editoras : BusinessEntity<Editoras>, IEditoras
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Nome = "NOME";
		}

        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 50
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
    }
}
