//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Biblioteca.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela LIVROS
    /// </summary>
    public partial interface ILivros : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        Benner.Biblioteca.Entidades.IAutores AutorInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        Handle AutorHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        Benner.Biblioteca.Entidades.IEditoras EditoraInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        Handle EditoraHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Emprestado (EMPRESTADO.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        System.Nullable<bool> Emprestado
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        Benner.Biblioteca.Entidades.IGeneros GeneroInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        Handle GeneroHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Número de Empréstimos (NMEMPRESTIMOS.)
        /// Opcional = S, Invisível = True, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        System.Nullable<long> NumeroEmprestimos
        {
            get;
            set;
        }
        
        /// <summary>
        /// Titulo (TITULO.)
        /// Opcional = N, Invisível = False, Tamanho = 100
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        string Titulo
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela LIVROS
    /// </summary>
    public partial interface ILivrosDao : IBusinessEntityDao<ILivros>
    {
    }
    
    /// <summary>
    /// DAO para a tabela LIVROS
    /// </summary>
    public partial class LivrosDao : BusinessEntityDao<Livros, ILivros>, ILivrosDao
    {
        
        public static LivrosDao CreateInstance()
        {
            return CreateInstance<LivrosDao>();
        }
    }
    
    /// <summary>
    /// Livros
    /// </summary>
    [EntityDefinitionName("LIVROS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Livros : BusinessEntity<Livros>, ILivros
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Autor = "AUTOR";
			public const string Editora = "EDITORA";
			public const string Emprestado = "EMPRESTADO";
			public const string Genero = "GENERO";
			public const string NumeroEmprestimos = "NMEMPRESTIMOS";
			public const string Titulo = "TITULO";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public Benner.Biblioteca.Entidades.IAutores AutorInstance
        {
            get
            {
                if (Autor.Handle == null)
                {
					return null;
                }
                return Autor.Instance;
            }
            set
            {
                if (value == null)
                {
					Autor = null;
					return;
                }
                Autor.Instance = (Benner.Biblioteca.Entidades.Autores) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public Handle AutorHandle
        {
            get
            {
                return Autor.Handle;
            }
            set
            {
                Autor.Handle = value;
            }
        }
        
        /// <summary>
        /// Autor (AUTOR.)
        /// Opcional = N, Invisível = False, Pesquisar = AUTORES
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Biblioteca.Entidades.Autores> Autor
        {
            get
            {
                return (Fields["AUTOR"] as EntityAssociation).Wrap<Benner.Biblioteca.Entidades.Autores>(Benner.Biblioteca.Entidades.Autores.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Autor.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Autor.Instance = value.Instance;
                    }
                    else
                    {
                        this.Autor.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public Benner.Biblioteca.Entidades.IEditoras EditoraInstance
        {
            get
            {
                if (Editora.Handle == null)
                {
					return null;
                }
                return Editora.Instance;
            }
            set
            {
                if (value == null)
                {
					Editora = null;
					return;
                }
                Editora.Instance = (Benner.Biblioteca.Entidades.Editoras) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public Handle EditoraHandle
        {
            get
            {
                return Editora.Handle;
            }
            set
            {
                Editora.Handle = value;
            }
        }
        
        /// <summary>
        /// Editora (EDITORA.)
        /// Opcional = N, Invisível = False, Pesquisar = EDITORAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Biblioteca.Entidades.Editoras> Editora
        {
            get
            {
                return (Fields["EDITORA"] as EntityAssociation).Wrap<Benner.Biblioteca.Entidades.Editoras>(Benner.Biblioteca.Entidades.Editoras.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Editora.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Editora.Instance = value.Instance;
                    }
                    else
                    {
                        this.Editora.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Emprestado (EMPRESTADO.)
        /// Opcional = N, Invisível = False, Default = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public System.Nullable<bool> Emprestado
        {
            get
            {
                return Fields["EMPRESTADO"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["EMPRESTADO"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public Benner.Biblioteca.Entidades.IGeneros GeneroInstance
        {
            get
            {
                if (Genero.Handle == null)
                {
					return null;
                }
                return Genero.Instance;
            }
            set
            {
                if (value == null)
                {
					Genero = null;
					return;
                }
                Genero.Instance = (Benner.Biblioteca.Entidades.Generos) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public Handle GeneroHandle
        {
            get
            {
                return Genero.Handle;
            }
            set
            {
                Genero.Handle = value;
            }
        }
        
        /// <summary>
        /// Genero (GENERO.)
        /// Opcional = N, Invisível = False, Pesquisar = GENEROS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Biblioteca.Entidades.Generos> Genero
        {
            get
            {
                return (Fields["GENERO"] as EntityAssociation).Wrap<Benner.Biblioteca.Entidades.Generos>(Benner.Biblioteca.Entidades.Generos.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Genero.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Genero.Instance = value.Instance;
                    }
                    else
                    {
                        this.Genero.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Número de Empréstimos (NMEMPRESTIMOS.)
        /// Opcional = S, Invisível = True, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Inteiro
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public System.Nullable<long> NumeroEmprestimos
        {
            get
            {
                return Fields["NMEMPRESTIMOS"] as System.Nullable<System.Int64>;
            }
            set
            {
                Fields["NMEMPRESTIMOS"] = value;
            }
        }
        
        /// <summary>
        /// Titulo (TITULO.)
        /// Opcional = N, Invisível = False, Tamanho = 100
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "17.2.0.0")]
        public string Titulo
        {
            get
            {
                return Fields["TITULO"] as System.String;
            }
            set
            {
                Fields["TITULO"] = value;
            }
        }
    }
}
