<%@ Page Title="Fluxo" Language="C#" Inherits="Benner.Tecnologia.Workflow.WebApp.WorkflowModelPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="FLUXO" Title="Fluxo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOS.ADM.FORM" IncludeRecordInRecentItems="True" UserDefinedLinkVisible="True" UserDefinedCommandsVisible="True" PageWidgetHandle="87" Level="15" Order="10"  />
        <wes:SimpleGrid runat="server" ID="PAPISDOFLUXO" Title="Papéis do fluxo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FLUXO" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOPAPEIS.ADM.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.MODELO = @CAMPO(HANDLE)" FormUrl="~/wfl/a/a/fluxopapel.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="88" Level="15" Order="20"  />
        <wes:SimpleGrid runat="server" ID="SUBFLUXOS" Title="Subfluxos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FLUXO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOSUBMODELOS.GRID" UserDefinedSelectColumnVisible="False" Mode="None" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.MODELO = @CAMPO(HANDLE)" FormUrl="~/wfl/a/a/fluxosubfluxo.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="89" Level="15" Order="25"  />
        <wes:SimpleGrid runat="server" ID="PERMISSOPARASUSPENDER" Title="Permissão para suspender" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FLUXO" ChromeState="Minimized" CanDelete="True" CanUpdate="True" CanInsert="True" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFMODELOSUSPENDERGRUPOS.ADM.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.MODELO = @CAMPO(HANDLE)" FormUrl="~/wfl/a/a/fluxosuspender.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="90" Level="15" Order="30"  />
        <wes:SimpleGrid runat="server" ID="PROCESSOSRELACIONADOS" Title="Processos relacionados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FLUXO" ChromeState="Minimized" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFPROCESSOS.ADM.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.HANDLE IN(SELECT F.PROCESSO FROM Z_WFPROCESSOMODELOS F WHERE F.MODELO=@CAMPO(HANDLE))" UserDefinedDisableRowSelection="False" PageWidgetHandle="91" Level="15" Order="40"  />
        </div>
    
      </asp:Content>
    