<%@ Page Title="Usuário" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AjaxForm runat="server" ID="USURIO" Title="Usuário" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_GRUPOUSUARIOS.ADM.FORM" IncludeRecordInRecentItems="True" UserDefinedLinkVisible="True" UserDefinedCommandsVisible="True" PageWidgetHandle="118" Level="15" Order="10"  />
        <wes:SimpleGrid runat="server" ID="USURIOSSUBSTITUTOS" Title="Substitutos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="USURIO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFUSUARIOSUBSTITUTOS.ADM.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.USUARIO = @CAMPO(HANDLE)" FormUrl="~/wfl/a/a/usuariosubstituto.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="119" Level="15" Order="20"  />
        <wes:SimpleGrid runat="server" ID="USURIOSRELACIONADOS" Title="Substituídos" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="USURIO" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFUSUARIOSUBSTITUTOS.ADM.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.SUBSTITUTO = @CAMPO(HANDLE)" UserDefinedDisableRowSelection="False" PageWidgetHandle="120" Level="15" Order="25"  />
        <wes:SimpleGrid runat="server" ID="PAPEISRELACIONADOS" Title="Papéis relacionados" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="USURIO" ChromeState="Normal" CanDelete="False" CanUpdate="False" CanInsert="False" SystemInstanceName="WORKFLOW" EntityViewName="Z_WFPAPEIS.ADM.GRID" UserDefinedSelectColumnVisible="False" Mode="Selectable" UserDefinedPageSize="10" DisplayRowCommand="True" CompanyFilterMode="None" UserDefinedCriteriaWhereClause="A.HANDLE IN (SELECT PAPEL FROM Z_WFPAPELUSUARIOS WHERE USUARIO = @CAMPO(HANDLE))" FormUrl="~/wfl/a/a/organogramapapel.aspx" UserDefinedDisableRowSelection="False" PageWidgetHandle="121" Level="15" Order="30"  />
        </div>
    
      </asp:Content>
    