<%@ Page Title="Home" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:AmCharts runat="server" ID="TESTESQL" Title="Livros Populares" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="TESTE.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Pie" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoicGllIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJwdWxsT3V0T25seU9uZSI6dHJ1ZSwiZXhwb3J0Ijp7ImVuYWJsZWQiOnRydWV9LCJ0aXRsZUZpZWxkIjoidGl0dWxvIiwidmFsdWVGaWVsZCI6Im5tZW1wcmVzdGltb3MiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsImJhbGxvb25UZXh0IjoiW1t0aXRsZV1dPGJyPjxzcGFuIHN0eWxlPSdmb250LXNpemU6MTRweCc+PGI+W1t2YWx1ZV1dPC9iPiAoW1twZXJjZW50c11dJSk8L3NwYW4+IiwibGFiZWxUZXh0IjoiW1t0aXRsZV1dOiBbW3ZhbHVlXV0iLCJsYWJlbHNFbmFibGVkIjp0cnVlLCJsZWdlbmQiOnsiZW5hYmxlZCI6ZmFsc2UsImFsaWduIjoiY2VudGVyIiwibWFya2VyVHlwZSI6ImNpcmNsZSJ9LCJpbm5lclJhZGl1cyI6IjAlIiwiYW5nbGUiOjMwLCJkZXB0aDNEIjozMH0=" PageWidgetHandle="190" Level="20" Order="20"  />
        <wes:AmCharts runat="server" ID="LIVROSPORSEXO" Title="Livros por Sexo" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="LIVROSPORSEXO.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" ChartType="Pie" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoicGllIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJwdWxsT3V0T25seU9uZSI6dHJ1ZSwiZXhwb3J0Ijp7ImVuYWJsZWQiOnRydWV9LCJ0aXRsZUZpZWxkIjoibGl2cm8iLCJ2YWx1ZUZpZWxkIjoiYyIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwiYmFsbG9vblRleHQiOiJbW3RpdGxlXV08YnI+PHNwYW4gc3R5bGU9J2ZvbnQtc2l6ZToxNHB4Jz48Yj5bW3ZhbHVlXV08L2I+IChbW3BlcmNlbnRzXV0lKTwvc3Bhbj4iLCJsYWJlbFRleHQiOiJbW3RpdGxlXV06IFtbdmFsdWVdXSIsImxhYmVsc0VuYWJsZWQiOnRydWUsImxlZ2VuZCI6eyJlbmFibGVkIjp0cnVlLCJhbGlnbiI6ImNlbnRlciIsIm1hcmtlclR5cGUiOiJjaXJjbGUiLCJsYWJlbFRleHQiOiJbW3RpdGxlXV0iLCJ2YWx1ZVRleHQiOiIiLCJwb3NpdGlvbiI6ImJvdHRvbSJ9LCJpbm5lclJhZGl1cyI6IjAlIiwiYW5nbGUiOjMwLCJkZXB0aDNEIjozMH0=" PageWidgetHandle="192" Level="20" Order="30"  />
        </div>
    
      </asp:Content>
    